#!/usr/bin/env python3
"""Remove deleted-addon plugin/autoload refs from project.godot."""
import re, os, sys

path = sys.argv[1] if len(sys.argv) > 1 else "project.godot"
if not os.path.exists(path):
    print(f"project.godot not found at {path}, skipping")
    sys.exit(0)

with open(path) as f:
    content = f.read()

before = content

# Remove enabled_plugins lines (regenerated by Godot on next load)
content = re.sub(r'^enabled_plugins=.*\n', '', content, flags=re.MULTILINE)
# Remove autoload entries pointing to deleted addon paths
content = re.sub(
    r'^[A-Za-z_]\w*=.*addons/(AdobeAnimateEditor|ModEditor)/.*\n',
    '', content, flags=re.MULTILINE
)
# Remove individual editor_plugins section lines for deleted addons
content = re.sub(r'^"res://addons/(AdobeAnimateEditor|ModEditor)/[^"]*"=true\n',
                 '', content, flags=re.MULTILINE)

with open(path, "w") as f:
    f.write(content)

removed = len(before.splitlines()) - len(content.splitlines())
print(f"project.godot cleaned ({removed} lines removed)")
