import sys
app_name, bundle_id, version, team_id = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
short_version = version
lines = [
    "[preset.0]",
    'name="iOS"',
    'platform="iOS"',
    "runnable=true",
    "advanced_options=false",
    "dedicated_server=false",
    'custom_features=""',
    'export_filter="all_resources"',
    'include_filter=""',
    'exclude_filter="*.cs"',
    'export_path="../PlantsVsZombiesHybrid.xcodeproj"',
    'encryption_include_filters=""',
    'encryption_exclude_filters=""',
    "encrypt_pck=false",
    "encrypt_directory=false",
    "",
    "[preset.0.options]",
    'custom_template/debug=""',
    'custom_template/release=""',
    'application/app_store_team_id="' + team_id + '"',
    'application/provisioning_profile_uuid_debug=""',
    'application/provisioning_profile_uuid_release=""',
    'application/name="' + app_name + '"',
    'application/info="Made with Godot Engine"',
    'application/signature=""',
    'application/version="' + version + '.0"',
    'application/bundle_identifier="' + bundle_id + '"',
    "application/categories=PackedStringArray()",
    'application/short_version="' + short_version + '"',
    'application/min_ios_version="16.0"',
    "application/orientation/portrait=false",
    "application/orientation/landscape_left=true",
    "application/orientation/landscape_right=true",
    "application/orientation/portrait_upside_down=false",
    'application/interruption_policy="stop"',
    "application/supports_opengl=false",
    "application/supports_metal=true",
    "application/supports_open_gles2=false",
    "application/supports_open_gles3=true",
    "application/supports_vulkan=false",
    'application/icon="res://icon.png"',
    'application/additional_plist_content=""',
    "capabilities/access_wifi=false",
    "capabilities/push_notifications=false",
    "capabilities/performance_gaming=false",
    "capabilities/performance_a12=false",
    "user_data/accessible_files_directories=PackedStringArray()",
    'architecture/target="arm64"',
    "application/export_method_debug=0",
    "application/export_method_release=0",
    'application/code_sign_identity_debug=""',
    'application/code_sign_identity_release=""',
]
with open("recovered/export_presets.cfg", "w") as f:
    f.write("\n".join(lines) + "\n")
print("export_presets.cfg generated")
